### ISSUE TITLE
When will the code of MetaAvatar be released?

### ISSUE THREAD

**Issue by vangoghcat** [taconite/PTF#4]
I am very interested in MetaAvatar on NeurIPS 2021
When will the code of MetaAvatar be released?
Look forward it. Thx !!!

**Comment by taconite** [comment]
Thanks for your interest in our work :)

Currently, I am working on another deadline so I have not been working on the code release of MetaAvatar. But the code of MetaAvatar should be available around NeurIPS conference proceedings, i.e. this December.

best,
Shaofei
